version: '3'
networks:
  backend:
services:
  yoga-graphql:
    build: .
    ports:
      - '4000:4444'
    env_file: variables.env
    environment:
      PRISMA_ENDPOINT: 'http://prisma:4466' #if put in env file will get error
      FRONTEND_URL: 'http://app:8080'
    depends_on:
      - prisma
      - postgres
    networks: 
      - backend
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    networks: 
      - backend
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    networks: 
      - backend
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~